apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  namespace: dev
spec:
  containers:
  - image: ubuntu
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: ubuntu-images
  restartPolicy: Always
