name: dev-env
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: actions/checkout@v2
      - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.pkg.github.com -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Checkout code
        uses: actions/checkout@v2
      - run: docker build -t ghcr.io/mercurial963/bookinfo-ratings:dev .
      - run: docker images
      - run: docker push ghcr.io/mercurial963/bookinfo-ratings:dev
